version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10.16.0
        working_directory: ~/repo
        steps:
            - run:
                  name: Install Dependencies
                  command: npm install firebase
            - run:
                  name: Install Dependencies
                  command: npm install firebase-tools
            - run:
                  name: Build
                  command: npm build
            - run:
                  name: Firebase Deploy
                  command: firebase deploy --token "$FIREBASE_TOKEN" --only hosting
