version: 2
jobs:
    build:
        branches:
            only:
                - master
        docker:
            - image: cimg/node:20.10.0
        working_directory: ~/repo
        steps:
        - checkout 
        - restore_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
        - run:
            name: Install Dependencies
            command: npm install
        - save_cache:
            key: dependency-cache-{{ checksum "package-lock.json" }}
            paths:
            - ./node_modules
        # - run:
        #     name: Build
        #     command: npm build
        - run:
            name: Firebase Deploy
            command: |
              echo $FIREBASE_KEY > credentials.json
              GOOGLE_APPLICATION_CREDENTIALS=credentials.json ./node_modules/.bin/firebase deploy

